phoenix-rtos/phoenix-rtos-doc

utils/psh.md
-added documentation of sysexec feature and sysexec features
JIRA: BES-148
=> psh: sysexec wildcards feature doc

utils/psh.md
=> psh: sysexec `*` wildcard documentation

utils/psh-applets/cat.md, utils/psh-applets/exec.md, utils/psh-applets/exit.md, utils/psh-applets/help.md, utils/psh-applets/history.md, utils/psh-applets/ls.md, utils/psh-applets/mkdir.md, utils/psh-applets/nc.md, utils/psh-applets/nslookup.md, utils/psh-applets/ping.md, utils/psh-applets/ps.md, utils/psh-applets/pshapp.md, utils/psh-applets/pshlogin.md, utils/psh-applets/runfile.md, utils/psh-applets/sysexec.md, utils/psh-applets/top.md, utils/psh-applets/touch.md, utils/psh.md
- added documentations for psh applets that are currently working
- update psh.md documentation
Documentation updates regarding phoenix-rtos/phoenix-rtos-utils#45
JIRA: BES-166
=> psh: further documentation development

utils/psh-applets/uptime.md, utils/psh.md
=> psh: add uptime

quickstart/armv7a7-imx6ull.md, quickstart/armv7m7-imxrt105x.md, quickstart/armv7m7-imxrt117x.md
=> imx6ull, imxrt105x and imxrt117x documentation blanks

quickstart/armv7m7-imxrt105x.md
=> quickstart: add imxrt105x info

quickstart/armv7a7-imx6ull.md, quickstart/armv7a9-zynq7000.md
=> quickstart: fast fixes

quickstart/armv7a7-imx6ull.md, quickstart/armv7a9-zynq7000.md
=> quickstart: fixes for website

quickstart/armv7m4-stm32l4x6.md, quickstart/armv7m7-imxrt106x.md
=> quickstart: minor fixes for website test

loader/README.md, loader/architecture.md, loader/cli.md
=> update loader documentation

loader/architecture.md
changed lists for better rendering outside of github
=> architecture md formatting fixes

README.md
=> update table of contents

libc/functions/README.md, libc/functions/f/freeaddrinfo.part-impl.md
=> add freeaddrinfo

quickstart/armv7a7-imx6ull.md, quickstart/armv7m4-stm32l4x6.md, quickstart/armv7m7-imxrt106x.md
=> quickstart: add USB ports info

libc/functions/README.md, libc/functions/g/gai_strerror.part-impl.md, libc/functions/g/getaddrinfo.part-impl.md, libc/functions/g/getchar.part-impl.md, libc/functions/g/getcwd.part-impl.md, libc/functions/g/getegid.part-impl.md, libc/functions/g/getline.part-impl.md, libc/functions/g/getpgrp.part-impl.md, libc/functions/g/getpid.part-impl.md, libc/functions/g/getppid.part-impl.md, libc/functions/g/getpwnam.part-impl.md, libc/functions/g/getpwuid.part-impl.md, libc/functions/g/gets.part-impl.md, libc/functions/g/getuid.part-impl.md
=> complete g functions

libc/functions/a/abort.part-impl.md, libc/functions/a/accept.part-impl.md, libc/functions/a/acos.part-impl.md, libc/functions/a/alarm.part-impl.md
=> update abort, accept, acos, alarm functions

quickstart/armv7a7-imx6ull.md
=> quickstart: update imx6ull

building/README.md, building/script.md, building/toolchain.md
=> building: website corrections

quickstart/armv7a7-imx6ull.md, quickstart/armv7a9-zynq7000-devboard.md, quickstart/armv7a9-zynq7000-emu.md, quickstart/armv7m4-stm32l4x6.md, quickstart/armv7m7-imxrt106x.md, quickstart/armv7m7-imxrt117x.md, quickstart/ia32-generic.md, quickstart/riscv64-virt.md
=> quickstart: corrections

building/toolchain.md, libc/functions/README.md, libc/functions/a/accept.part-impl.md, libc/functions/e/exp.part-impl.md, libc/functions/f/fmod.part-impl.md, libc/functions/f/fnmatch.part-impl.md, libc/functions/f/fscanf.part-impl.md, libc/functions/m/mkfifo.part-impl.md, libc/functions/m/mmap.part-impl.md, libc/functions/m/munmap.part-impl.md, libc/functions/p/printf.part-impl.md, libc/functions/s/sigaddset.part-impl.md, libc/functions/s/signal.part-impl.md, libc/functions/s/sigprocmask.part-impl.md, libc/functions/s/sigsuspend.part-impl.md, libc/functions/t/tanh.part-impl.md, libc/functions/t/tcflush.part-impl.md, libc/functions/u/unlink.part-impl.md, libc/functions/u/utime.part-impl.md
=> libc functions: markdown corrections

libc/functions/a/abort.part-impl.md, libc/functions/a/acos.part-impl.md, libc/functions/a/alarm.part-impl.md, libc/functions/f/fopen.part-impl.md
=> libc: small corrections in functions documentation

libc/functions/README.md, libc/functions/g/getline.part-impl.md, libc/functions/s/setbuf.part-impl.md
=> libc: add setbuf and website fixes

libc/functions/g/getline.part-impl.md
=> libc: corrections for website

coding.md, kernel/hal/ia32.md, kernel/hal/riscv64.md
=> corrections for highlighting on website

libc/functions/m/msgrecv.phrtos.md, libc/functions/m/msgrespond.phrtos.md, libc/functions/m/msgsend.phrtos.md
=> msgSend(), msgRecv(), msgRespond() functions documentation

utils/psh-applets/echo.md, utils/psh.md
=> psh: Added echo documentation

utils/psh-applets/pm.md, utils/psh.md
=> psh: Added pm documentation

kernel/syscalls/README.md
As title says, general description of system calls with an example presenting procedure of adding new system call.
=> kernel/syscall: add general description of Phoenix-RTOS system calls

devices/interrupts.md
=> interrupt() correction

building/README.md
=> building: add mtd-utils to required tools

libc/functions/README.md, libc/functions/s/setgid.not-impl.md, libc/functions/w/wcscmp.impl.md, libc/functions/w/wcslen.non-impl.md
=> libc: add wcscmp documentation

ports/mbedtls.md
=> ports: correct mbedtls documentation

README.md, devices/libsdio/README.md
=> libsdio: create libsdio API documentation

utils/psh-applets/ntpclient.md, utils/psh.md
=> utils/psh: Add ntpclient applet description

corelibs/README.md, corelibs/libswdg.md
=> Add libswdg documentation

kernel/proc/README.md, kernel/proc/forking.md, kernel/proc/msg.md, kernel/proc/namespace.md, kernel/proc/scheduler.md, kernel/proc/sync.md
Add scheduler description.
PD-314
=> kernel/proc: add scheduler description

libc/functions/README.md, libc/functions/f/feof.impl.md, libc/functions/f/ferror.impl.md, libc/functions/f/fputs.part-impl.md, libc/functions/p/pclose.part-impl.md, libc/functions/p/popen.part-impl.md, libc/functions/v/vprintf.part-impl.md, libc/functions/v/vscanf.part-impl.md
Ordering and adding missing docs for stdio functions
DONE: PD-331
=> libc: complete documentation for stdio functions

tests/README.md
Added missing section about installing pip dependencies .
DONE: RTOS-349
=> Added section about tests setup

libc/functions/README.md, libc/functions/i/ioctl.part-impl.md
=> add ioctl() documentation

building/toolchain.md
=> Update toolchains list

building/README.md
=> building: add installing libelf on macOS

quickstart/armv7a9-zynq7000-zturn.md
=> quickstart: minor correct to zturn quickstart

kernel/syscalls/ipc.md
=> Adapt to msgRecv, msgRespond API change

utils/psh-applets/ping.md
JIRA: CI-350
Based on:
https://github.com/phoenix-rtos/phoenix-rtos-project/issues/851
=> psh: ping: remove info about min interval

kernel/vm/page.md
Added table that explains every letter seen in  page allocator.
=> doc: Add explanation of letters in page allocator.

devices/hwaccess.md, libc/functions/m/mmap.part-impl.md
=> Adjust mmap doc to new interface

building/README.md, quickstart/ia32-generic-qemu.md
=> doc: fix lists formatting

README.md, devices/sensors/sensorhub.md, devices/sensors/simsensors.md
=> Simsensor docs

corelibs/libcache.md, corelibs/libswdg.md, corelibs/libuuid.md
=> doc: add alternative names of libraries to docs

devices/interface.md, kernel/msg/README.md
JIRA: RTOS-792
Add updated message documentation.
=> kernel: add msg documentation

kernel/syscalls/sync.md, libc/functions/index.md, libc/functions/sys/threads/condCreateWithAttr.phrtos.md, libc/functions/sys/threads/condSignal.phrtos.md, libc/functions/sys/threads/condWait.phrtos.md, libc/functions/sys/threads/mutexCreate.phrtos.md, libc/functions/sys/threads/mutexCreateWithAttr.phrtos.md
=> libc: update cond and mutex functions documentation

quickstart/sparcv8leon3-gr712rc-board.md
=> quickstart/gr712rc: fix index links

utils/psh/psh-applets/top.md
=> fix bullet list elements not printed when starting with %

index.md
=> index.md: change wrong link name of mimas target

_static/css/furo-phoenix.css
=> css: hide theme-toggle icon

coding/index.md
=> coding: Update file header convention

kernel/syscalls/file.md
=> kernel/syscalls/file: add sysvfs syscall decription

_static/css/furo-phoenix.css
=> Fix margin in sphinx theme on mobile/print view
